// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  footer: dynamic(() => import("./Footer")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  project: dynamic(() => import("./Project")),
  project_navigation: dynamic(() => import("./ProjectNavigation")),
};
