// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  c_vpdf: dynamic(() => import("./CVpdf")),
  footer: dynamic(() => import("./Footer")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  lyd_projekt: dynamic(() => import("./LydProjekt")),
  project: dynamic(() => import("./Project")),
  project_navigation: dynamic(() => import("./ProjectNavigation")),
  so_me: dynamic(() => import("./SoMe")),
};
